PVTSystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from PVTSystem import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^appointment/', include('appointment.urls', namespace='appointment')),
    url(r'^patient/', include('patient.urls', namespace='patient')),
    url(r'^doctor/', include('doctor.urls', namespace='doctor')),
    url(r'^examination/', include('examination.urls', namespace='examination')),
    url(r'^diagnosis/', include('diagnosis.urls', namespace='diagnosis')),
    url(r'^account/', include('accounts.urls')),
    #url(r'^accounts/logout/', auth_views.logout, name='logout', kwargs={'next_page': settings.LOGIN_URL,}),
    url(r'^login/', include('accounts.urls', namespace='login')),
]

appointment/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.appointment_list, name='appointment_list'),

	url(r'^(?P<pk>\d+)/$', views.appointment_detail, name='appointment_detail'),

	url(r'^new/$', views.appointment_new, name='appointment_new'),

	url(r'^(?P<appointment_pk>\d+)/appointment/(?P<pk>\d+)/edit/$', views.appointment_edit, name='appointment_edit'),

	url(r'^(?P<appointment_pk>\d+)/appointment/(?P<pk>\d+)/delete/$', views.appointment_delete, name='appointment_delete'),
]

diagnosis/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.diagnosis_list, name='diagnosis_list'),
	url(r'^(?P<pk>\d+)/$', views.diagnosis_detail, name='diagnosis_detail'),
	url(r'^new/$', views.diagnosis_new, name='diagnosis_new'),
	url(r'^(?P<diagnosis_pk>\d+)/diagnosis/(?P<pk>\d+)/edit/$', views.diagnosis_edit, name='diagnosis_edit'),
	url(r'^(?P<diagnosis_pk>\d+)/diagnosis/(?P<pk>\d+)/delete/$', views.diagnosis_delete, name='diagnosis_delete'),
	url(r'^(?P<diagnosis_pk>\d+)/diagnosis/(?P<pk>\d+)/transfer/$', views.diagnosis_transfer, name='diagnosis_transfer'),
    url(r'^(?P<diagnosis_pk>\d+)/diagnosis/(?P<pk>\d+)/transfer/$', views.diagnosis_edit, name='sendingPrescription'),

 ]

doctor/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.doctor_list, name='doctor_list'),
	url(r'^(?P<pk>\d+)/$', views.doctor_detail, name='doctor_detail'),
	url(r'^new/$', views.doctor_new, name='doctor_new'),
	url(r'^(?P<doctor_pk>\d+)/doctor/(?P<pk>\d+)/edit/$', views.doctor_edit, name='doctor_edit'),
	url(r'^(?P<doctor_pk>\d+)/doctor/(?P<pk>\d+)/delete/$', views.doctor_delete, name='doctor_delete'),
]

examination/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.examination_list, name='examination_list'),
	url(r'^(?P<pk>\d+)/$', views.examination_detail, name='examination_detail'),
	url(r'^new/$', views.examination_new, name='examination_new'),
	url(r'^(?P<examination_pk>\d+)/examination/(?P<pk>\d+)/edit/$', views.examination_edit, name='examination_edit'),
	url(r'^(?P<examination_pk>\d+)/examination/(?P<pk>\d+)/delete/$', views.examination_delete, name='examination_delete'),
	url(r'^(?P<examination_pk>\d+)/examination/(?P<pk>\d+)/transfer/$', views.examination_transfer, name='examination_transfer'),
 ]

appointment/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

class Appointment(models.Model):
	app_id = models.CharField(max_length=200)
	doctor_id = models.ForeignKey('doctor.Doctor', default="", null=False)
	user = models.ForeignKey(User, default="", null=False)


	def __str__(self):
		return self.app_id

	def get_absolute_url(self):
		return reverse('appointment:appointment_list')

appointment/forms.py
from django import forms
from .models import Appointment

class AddAppointmentForm(forms.ModelForm):
	class Meta:
		model = Appointment
		fields = (
			'doctor_id',
			'user',
			'app_id'
		)

appointment/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Appointment
from .forms import AddAppointmentForm
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import (authenticate, login, get_user_model, logout,)
from django.views.generic import View



#appointment_list = ListView.as_view(model=Appointment)

appointment_list = ListView.as_view(queryset=Appointment.objects.order_by('app_id')[:10],
               context_object_name='appointment_list',
               template_name='appointment/appointment_list.html')


'''

def appointment_list(request):
    print(request.user) #test13
    print(request.user.id)  # test13
    args = {'user': request.user}
    #print(args)
    return render(request, 'appointment/appointment_list.html', args)

'''
appointment_detail = DetailView.as_view(model=Appointment)

appointment_new = CreateView.as_view(model=Appointment, form_class=AddAppointmentForm)

appointment_edit = UpdateView.as_view(model=Appointment, form_class=AddAppointmentForm)

appointment_delete = DeleteView.as_view(model=Appointment, success_url=reverse_lazy('appointment:appointment_list'))

appointment/templates/appointment/appointment_confirm_delete.html
{% extends "appointment/layout.html" %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<form action="" method="post">
                {% csrf_token %}
                <div class="alert alert-danger">
                Are you really sure to delete it?
                </div>
                <table>
                    {{ form.as_table }}
                </table>
                <input type="submit" value="Delete" class="btn btn-primary"/>
                <a href="{% url "appointment:appointment_list" %}" class="btn btn-primary">Back to the List</a>
            </form>
		</div>
	</div>
</div>

{% endblock %}

appointment/templates/appointment/appointment_detail.html
{% extends "appointment/layout.html" %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-12">
        <h1>APPOINTMENT - DETAIL</h1><br>
          <hr/>
      <div class="form-group">
            <label for="">Appointment Number</label>
            <input type="text" name="app_id" value="{{ appointment.app_id }}" class="form-control" id="app_id" placeholder="" disabled>
      </div>
      <div class="form-group">
            <label for="">Doctor Name</label>
            <input type="text" name="doctor_id" value="{{ appointment.doctor_id }}" class="form-control" id="doctor_id" placeholder="" disabled>
      </div>
      <div class="form-group">
            <label for="">User Name</label>
            <input type="text" name="user_id" value="{{ appointment.user }}" class="form-control" id="date" placeholder="" disabled>
      </div>
          <a href="{% url "appointment:appointment_list" %}" class="btn btn-primary">List</a>
        {% if user.id == 1 %}
          <a href="{% url "appointment:appointment_edit" appointment.pk appointment.pk %}" class="btn btn-primary">Edit</a>
          <a href="{% url "appointment:appointment_delete" appointment.pk appointment.pk %}" class="btn btn-primary">Delete</a>
          <a href="{% url "examination:examination_transfer" appointment.app_id appointment.user_id%}" class="btn btn-primary">Examination</a>
        {% endif %}
    </div>
  </div>
</div>
{% endblock %}

appointment/templates/appointment/appointment_form.html
{% extends "appointment/layout.html" %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-sm-12">
            <h1>APPOINTMENT - ADD </h1>
			<form action="" method="post">
                {% csrf_token %}
                <table>
                    {{ form.as_p }}
                </table>
                <input type="submit" />
            </form>
		</div>
	</div>
</div>

{% endblock %}

appointment/templates/appointment/appointment_list.html
{% extends "appointment/layout.html" %}

{% block head %}
<title>Appointment</title>
{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-sm-12">
        <h1>APPOINTMENT - LIST</h1>
            {% if user.is_authenticated %}
                {% if user.id == 1 %}
			        <table class="table table-hover table-bordered">
				        <a href="{% url "appointment:appointment_new" %}" class="btn btn-primary">Add Appointment</a>
			        </table>
                {% endif %}
			<table class="table table-hover table-bordered">
             <thead>
                    <tr>
                        <th>ID</th>
                        <th>Appoint Number</th>
                        <th>First Name</th>
                        <th>User ID</th>
                    </tr>
                </thead>
                <tbody>

                {% for appointment in appointment_list %}
                {% if user.id == appointment.user.id or user.id == 1 %}
                    <tr>
                        <td width="130" align="center"><a href="{% url "appointment:appointment_detail" appointment.pk %}">{{ appointment.pk}}</a></td>
                        <td>{{ appointment.app_id}}</td>
                        <td>{{ appointment.doctor_id}}</td>
                        <td>{{ appointment.user.id}}</td>
                        </td>
                    </tr>
                    {% else %}
            {% endif %}
                {% endfor %}
                 </tbody>
			</table>

			</table>
             {% else %}
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/account/login/">Login</a></li>
            <li><a href="/account/register">Register</a></li>
          </ul>
        {% endif %}
		</div>
	</div>
</div>
{% endblock %}

appointment/templates/appointment/index.html
<div class="container">
	<table class="table table-striped">
		<thead>
		<tr align="middle">
			<td><B>Appointment ID</B></td>
			<td><B>Patient Name</B></td>
			<td><B>Doctor Name</B></td>
			<td><B>Appointment_Date</B></td>
			<td><B>Created_Date ID</B></td>
			<td><B>Updated_Date ID</B></td>
		</tr>
		</thead>
	</table>
</div>

appointment/templates/appointment/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>{% block title %}{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6.js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">PVTS</a>&nbsp
        </div>

        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'view_profile' %}">Profile</a></li>&nbsp
            <li><a class="navbar-brand" href="{% url 'doctor:doctor_list' %}">Doctor</a><li>&nbsp
            <li><a class="navbar-brand" href="{% url 'appointment:appointment_list' %}">Appointment</a><li>&nbsp
            <li><a class="navbar-brand" href="{% url 'examination:examination_list' %}">Examination</a><li>&nbsp
            <li><a class="navbar-brand" href="{% url 'diagnosis:diagnosis_list' %}">Diagnosis</a><li>&nbsp
          </ul>
             <ul class="nav navbar-nav navbar-right">
            <li>{{ user.id }}</li>&nbsp
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/account/logout/">Logout</a></li>&nbsp
          </ul>
        </div><!--/.nav-collapse -->

      </div>
    </nav>
    <div style="padding-top:100px">
    </div>
	{% block content %}
	{% endblock %}
	<hr/>
</body>
</html>

appointment/templates/appointment/registration_form.html
{% extends "appointment/layout.html" %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-sm-12">
            <div class="panel-default">
                <div class="panel-body">
			        <h3>Create a New Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post">
                        {% csrf_token %}
                        dddddddddddddd
                        {% include 'appointment/registration_form.html' %}
                        <table>
                        {{ form.as_table }}
                        </table>
                        <input type="submit" />
                    </form>
                </div>
            </div>
		</div>
	</div>
</div>

{% endblock %}