PVTSystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from PVTSystem import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^appointment/', include('appointment.urls', namespace='appointment')),
    url(r'^patient/', include('patient.urls', namespace='patient')),
    url(r'^doctor/', include('doctor.urls', namespace='doctor')),
    url(r'^examination/', include('examination.urls', namespace='examination')),
    url(r'^diagnosis/', include('diagnosis.urls', namespace='diagnosis')),
    url(r'^account/', include('accounts.urls')),
    #url(r'^accounts/logout/', auth_views.logout, name='logout', kwargs={'next_page': settings.LOGIN_URL,}),
    url(r'^login/', include('accounts.urls', namespace='login')),
]

appointment/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.appointment_list, name='appointment_list'),

	url(r'^(?P<pk>\d+)/$', views.appointment_detail, name='appointment_detail'),

	url(r'^new/$', views.appointment_new, name='appointment_new'),

	url(r'^(?P<appointment_pk>\d+)/appointment/(?P<pk>\d+)/edit/$', views.appointment_edit, name='appointment_edit'),

	url(r'^(?P<appointment_pk>\d+)/appointment/(?P<pk>\d+)/delete/$', views.appointment_delete, name='appointment_delete'),
]

diagnosis/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.diagnosis_list, name='diagnosis_list'),
	url(r'^(?P<pk>\d+)/$', views.diagnosis_detail, name='diagnosis_detail'),
	url(r'^new/$', views.diagnosis_new, name='diagnosis_new'),
	url(r'^(?P<diagnosis_pk>\d+)/diagnosis/(?P<pk>\d+)/edit/$', views.diagnosis_edit, name='diagnosis_edit'),
	url(r'^(?P<diagnosis_pk>\d+)/diagnosis/(?P<pk>\d+)/delete/$', views.diagnosis_delete, name='diagnosis_delete'),
	url(r'^(?P<diagnosis_pk>\d+)/diagnosis/(?P<pk>\d+)/transfer/$', views.diagnosis_transfer, name='diagnosis_transfer'),
    url(r'^(?P<diagnosis_pk>\d+)/diagnosis/(?P<pk>\d+)/transfer/$', views.diagnosis_edit, name='sendingPrescription'),

 ]

doctor/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.doctor_list, name='doctor_list'),
	url(r'^(?P<pk>\d+)/$', views.doctor_detail, name='doctor_detail'),
	url(r'^new/$', views.doctor_new, name='doctor_new'),
	url(r'^(?P<doctor_pk>\d+)/doctor/(?P<pk>\d+)/edit/$', views.doctor_edit, name='doctor_edit'),
	url(r'^(?P<doctor_pk>\d+)/doctor/(?P<pk>\d+)/delete/$', views.doctor_delete, name='doctor_delete'),
]

examination/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.examination_list, name='examination_list'),
	url(r'^(?P<pk>\d+)/$', views.examination_detail, name='examination_detail'),
	url(r'^new/$', views.examination_new, name='examination_new'),
	url(r'^(?P<examination_pk>\d+)/examination/(?P<pk>\d+)/edit/$', views.examination_edit, name='examination_edit'),
	url(r'^(?P<examination_pk>\d+)/examination/(?P<pk>\d+)/delete/$', views.examination_delete, name='examination_delete'),
	url(r'^(?P<examination_pk>\d+)/examination/(?P<pk>\d+)/transfer/$', views.examination_transfer, name='examination_transfer'),
 ]

examination/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

class Examination(models.Model):
	exam_id = models.AutoField(primary_key=True)
	app_id = models.OneToOneField('appointment.Appointment', default="", null=False)
	user = models.ForeignKey(User, default="", null=False)
	doctor_id = models.ForeignKey('doctor.Doctor', default="", null=False)
	weight = models.CharField(max_length=200)
	temperature = models.CharField(max_length=200)
	blood_pressure = models.CharField(max_length=20)
	respiration = models.CharField(max_length=20)
	heart_rate = models.CharField(max_length=20)
	reflex = models.CharField(max_length=20)
	visual_activity = models.CharField(max_length=20)
	ears = models.CharField(max_length=20)
	skin_polar = models.CharField(max_length=20)
	lungs = models.CharField(max_length=20)
	throat = models.CharField(max_length=20)
	interview_note = models.TextField()
	created_date = models.DateTimeField(auto_now_add=True)
	updated_date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.weight

	def get_absolute_url(self):
		return reverse('examination:examination_list')

examination/forms.py
from django import forms
from .models import Examination

class AddExaminationForm(forms.ModelForm):
	class Meta:
		model = Examination
		fields = '__all__'

examination/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Examination
from .forms import AddExaminationForm
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy

#for Transfer result of examination

from diagnosis.models import Diagnosis
from diagnosis.forms import AddDiagnosisForm

examination_list = ListView.as_view(model = Examination)

examination_detail = DetailView.as_view(model = Examination)

examination_new = CreateView.as_view(model = Examination, form_class=AddExaminationForm)

examination_edit = UpdateView.as_view(model = Examination, form_class=AddExaminationForm)

examination_delete = DeleteView.as_view(model = Examination, success_url=reverse_lazy('examination:examination_list'))

examination_transfer = CreateView.as_view(model = Examination, form_class=AddExaminationForm)

examination/templates/examination/examination_confirm_delete.html
{% extends "examination/layout.html" %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<form action="" method="post">
	            {% csrf_token %}
	            <div class="alert alert-danger">
	            Are you really sure to delete it?
                </div>
                <table>
                    {{ form.as_table }}
                </table>
                <input type="submit" value="Delete" class="btn btn-primary"/>
                <a href="{% url "examination:examination_list" %}" class="btn btn-primary">Back to the List</a>
            </form>
		</div>
	</div>
</div>

{% endblock %}

examination/templates/examination/examination_detail.html
{% extends "examination/layout.html" %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>EXAMINATION - DETAIL </h1>
        <div class="form-group">
            <label for="">Examination Number</label>
            <input type="text" name="doctor_id" value="{{ examination.exam_id}}" class="form-control" id="fname" placeholder="" disabled>
        </div>
        <div class="form-group">
            <label for="">Appointment Number</label>
            <input type="text" name="First Name" value="{{ examination.app_id }}" class="form-control" id="fname" placeholder="" disabled>
        </div>
        <div class="form-group">
            <label for="">Doctor Name</label>
            <input type="text" name="Mname" value="{{ examination.doctor_id }}" class="form-control" id="Mname" placeholder="" disabled>
        </div>
        <div class="form-group">
            <label for="">Last Name</label>
            <input type="text" name="lname" value="{{ examination.app_id }}" class="form-control" id="lname" placeholder="" disabled>
        </div>
        <div class="form-group">
            <label for="">Weight</label>
            <input type="text" name="mname" value="{{ examination.weight }}" class="form-control" id="dob" placeholder="" disabled>
        </div>
        <div class="form-group">
            <label for="">Temperature</label>
            <input type="text" name="mname" value="{{ examination.temperature }}" class="form-control" id="sex" placeholder="" disabled>
        </div>
        <div class="form-group">
            <label for="">Blood Pressure 1</label>
            <input type="text" name="mname" value="{{ examination.blood_pressure }}" class="form-control" id="addr1" placeholder="" disabled>
        </div>
        <div class="form-group">
            <label for="">Respiration</label>
            <input type="text" name="mname" value="{{ examination.respiration }}" class="form-control" id="addr2" placeholder="" disabled>
        </div>
        <div class="form-group">
            <label for="">Heart Rate</label>
            <input type="text" name="mname" value="{{ examination.heart_rate }}" class="form-control" id="addr3" placeholder="" disabled>
        </div>
        <div class="form-group">
            <label for="">Reflex</label>
            <input type="text" name="city" value="{{ examination.reflex }}" class="form-control" id="city" placeholder="" disabled>
        </div>
        <div class="form-group">
            <label for="">Visual Activity</label>
            <input type="text" name="state" value="{{ examination.visual_activity }}" class="form-control" id="state" placeholder="" disabled>
        </div>
        <div class="form-group">
            <label for="">Ears</label>
            <input type="text" name="country" value="{{ examination.ears }}" class="form-control" id="country" placeholder="" disabled>
        </div>
        <div class="form-group">
            <label for="">Skin Polar</label>
            <input type="text" name="phone1" value="{{ examination.skin_polar }}" class="form-control" id="phone1" placeholder="" disabled>
        </div>
        <div class="form-group">
            <label for="">Lungs</label>
            <input type="text" name="phone2" value="{{ examination.lungs }}" class="form-control" id="phone2" placeholder="" disabled>
        </div>
        <div class="form-group">
            <label for="">Throat</label>
            <input type="text" name="phone3" value="{{ examination.throat }}" class="form-control" id="phone3" placeholder="" disabled>
        </div>
        <div class="form-group">
            <label for="">Interview Note</label>
            <input type="text" name="phone3" value="{{ examination.interview_note }}" class="form-control" id="phone3" placeholder="" disabled>
        </div>
          <hr/>
          <a href="{% url "examination:examination_list" %}" class="btn btn-primary">List</a>
          <a href="{% url "examination:examination_edit" examination.pk examination.pk %}" class="btn btn-primary">Edit</a>
          <a href="{% url "examination:examination_delete" examination.pk examination.pk %}" class="btn btn-primary">Delete</a>
          <a href="{% url "diagnosis:diagnosis_transfer" examination.pk examination.pk %}" class="btn btn-primary">Transfer to Doctor</a>
    </div>
  </div>
</div>
{% endblock %}

examination/templates/examination/examination_form.html
{% extends "examination/layout.html" %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-sm-12">
            <h1>EXAMINATION - ADD </h1>
        </div>
			<form action="" method="post">
	        {% csrf_token %}
	            <table>
		        {{ form.as_table }}
	            </table>
            <input type="submit" />
            </form>
		</div>
	</div>
</div>

{% endblock %}

examination/templates/examination/examination_list.html
{% extends "examination/layout.html" %}

{% block head %}
<title>Examination</title>
{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-sm-12">
        <h1>EXAMINATION - LIST</h1>
            {% if user.is_authenticated %}
			<table class="table table-hover table-bordered">
             <thead>
                    <tr>
                        <th>ID</th>
                        <th>Appoint Number</th>
                        <th>First Name</th>
                        <th>User ID</th>
                    </tr>
                </thead>
                <tbody>

                {% for examination in examination_list %}
                {% if user.id == 1 %}
                    <tr>
                        <td width="130" align="center"><a href="{% url "examination:examination_detail" examination.pk %}">{{ examination.pk}}</a></td>
                        <td>{{ examination.app_id}}</td>
                        <td>{{ examination.doctor_id}}</td>
                        <td>{{ examination.user.id}}</td>
                        </td>
                    </tr>
                    {% else %}
            {% endif %}
                {% endfor %}
                 </tbody>
			</table>

			</table>
             {% else %}
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/account/login/">Login</a></li>
            <li><a href="/account/register">Register</a></li>
          </ul>
        {% endif %}
		</div>
	</div>
</div>
{% endblock %}

examination/templates/examination/index.html
<div class="container">
	<table class="table table-striped">
		<thead>
		<tr align="middle">
			<td><B>Appointment ID</B></td>
			<td><B>Patient Name</B></td>
			<td><B>Doctor Name</B></td>
			<td><B>Appointment_Date</B></td>
			<td><B>Created_Date ID</B></td>
			<td><B>Updated_Date ID</B></td>
		</tr>
		</thead>
	</table>
</div>

examination/templates/examination/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>{% block title %}{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6.js/bootstrap.min.js"></script>
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">PVTS</a>&nbsp
        </div>
        {% if user.is_authenticated %}
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'view_profile' %}">Profile</a></li>&nbsp
            <li><a class="navbar-brand" href="{% url 'doctor:doctor_list' %}">Doctor</a><li>&nbsp
            <li><a class="navbar-brand" href="{% url 'appointment:appointment_list' %}">Appointment</a><li>&nbsp
            <li><a class="navbar-brand" href="{% url 'examination:examination_list' %}">Examination</a><li>&nbsp
            <li><a class="navbar-brand" href="{% url 'diagnosis:diagnosis_list' %}">Diagnosis</a><li>&nbsp
          </ul><ul class="nav navbar-nav navbar-right">
            <li><a href="/account/logout/">Logout</a></li>&nbsp
          </ul>
        </div><!--/.nav-collapse -->
        {% else %}
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/account/login/">Login</a></li>
            <li><a href="/account/register">Register</a></li>
          </ul>
        {% endif %}
      </div>
    </nav>
    <div style="padding-top:100px">
    </div>
	{% block content %}
	{% endblock %}

	<hr/>
</body>
</html>