PVTSystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from PVTSystem import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^appointment/', include('appointment.urls', namespace='appointment')),
    url(r'^patient/', include('patient.urls', namespace='patient')),
    url(r'^doctor/', include('doctor.urls', namespace='doctor')),
    url(r'^examination/', include('examination.urls', namespace='examination')),
    url(r'^diagnosis/', include('diagnosis.urls', namespace='diagnosis')),
    url(r'^account/', include('accounts.urls')),
    #url(r'^accounts/logout/', auth_views.logout, name='logout', kwargs={'next_page': settings.LOGIN_URL,}),
    url(r'^login/', include('accounts.urls', namespace='login')),
]

appointment/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.appointment_list, name='appointment_list'),

	url(r'^(?P<pk>\d+)/$', views.appointment_detail, name='appointment_detail'),

	url(r'^new/$', views.appointment_new, name='appointment_new'),

	url(r'^(?P<appointment_pk>\d+)/appointment/(?P<pk>\d+)/edit/$', views.appointment_edit, name='appointment_edit'),

	url(r'^(?P<appointment_pk>\d+)/appointment/(?P<pk>\d+)/delete/$', views.appointment_delete, name='appointment_delete'),
]

diagnosis/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.diagnosis_list, name='diagnosis_list'),
	url(r'^(?P<pk>\d+)/$', views.diagnosis_detail, name='diagnosis_detail'),
	url(r'^new/$', views.diagnosis_new, name='diagnosis_new'),
	url(r'^(?P<diagnosis_pk>\d+)/diagnosis/(?P<pk>\d+)/edit/$', views.diagnosis_edit, name='diagnosis_edit'),
	url(r'^(?P<diagnosis_pk>\d+)/diagnosis/(?P<pk>\d+)/delete/$', views.diagnosis_delete, name='diagnosis_delete'),
	url(r'^(?P<diagnosis_pk>\d+)/diagnosis/(?P<pk>\d+)/transfer/$', views.diagnosis_transfer, name='diagnosis_transfer'),
    url(r'^(?P<diagnosis_pk>\d+)/diagnosis/(?P<pk>\d+)/transfer/$', views.diagnosis_edit, name='sendingPrescription'),

 ]

doctor/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.doctor_list, name='doctor_list'),
	url(r'^(?P<pk>\d+)/$', views.doctor_detail, name='doctor_detail'),
	url(r'^new/$', views.doctor_new, name='doctor_new'),
	url(r'^(?P<doctor_pk>\d+)/doctor/(?P<pk>\d+)/edit/$', views.doctor_edit, name='doctor_edit'),
	url(r'^(?P<doctor_pk>\d+)/doctor/(?P<pk>\d+)/delete/$', views.doctor_delete, name='doctor_delete'),
]

examination/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.examination_list, name='examination_list'),
	url(r'^(?P<pk>\d+)/$', views.examination_detail, name='examination_detail'),
	url(r'^new/$', views.examination_new, name='examination_new'),
	url(r'^(?P<examination_pk>\d+)/examination/(?P<pk>\d+)/edit/$', views.examination_edit, name='examination_edit'),
	url(r'^(?P<examination_pk>\d+)/examination/(?P<pk>\d+)/delete/$', views.examination_delete, name='examination_delete'),
	url(r'^(?P<examination_pk>\d+)/examination/(?P<pk>\d+)/transfer/$', views.examination_transfer, name='examination_transfer'),
 ]

patient/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.patient_list, name='patient_list'),
	url(r'^(?P<pk>\d+)/$', views.patient_detail, name='patient_detail'),
	url(r'^new/$', views.patient_new, name='patient_new'),
	url(r'^(?P<patient_pk>\d+)/patient/(?P<pk>\d+)/edit/$', views.patient_edit, name='patient_edit'),
	url(r'^(?P<patient_pk>\d+)/patient/(?P<pk>\d+)/delete/$', views.patient_delete, name='patient_delete'),
]

patient/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Patient(models.Model):
	date = models.DateTimeField(auto_now_add=True)
	patient_id = models.AutoField(primary_key=True)
	fname = models.CharField(max_length=200)
	mname = models.CharField(max_length=200)
	lname = models.CharField(max_length=200)
	dob = models.CharField(max_length=20)
	sex = models.CharField(max_length=20)
	addr1 = models.CharField(max_length=20)
	addr2 = models.CharField(max_length=20)
	addr3 = models.CharField(max_length=20)
	city = models.CharField(max_length=20)
	county = models.CharField(max_length=20)
	state = models.CharField(max_length=20)
	country = models.CharField(max_length=20)
	zipcode = models.CharField(max_length=20)
	phone1 = models.CharField(max_length=20)
	phone2 = models.CharField(max_length=20)
	phone3 = models.CharField(max_length=20)

	created_date = models.DateTimeField(auto_now_add=True)
	updated_date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.fname

	def get_absolute_url(self):
		return reverse('patient:patient_list')

patient/forms.py
from django import forms
from .models import Patient

class AddPatientForm(forms.ModelForm):
	class Meta:
		model = Patient
		fields = '__all__'

patient/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Patient
from .forms import AddPatientForm
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.utils import timezone



patient_list = ListView.as_view(model=Patient)

patient_detail = DetailView.as_view(model=Patient)

patient_new = CreateView.as_view(model=Patient, form_class=AddPatientForm)

patient_edit = UpdateView.as_view(model=Patient, form_class=AddPatientForm)

patient_delete = DeleteView.as_view(model=Patient, success_url=reverse_lazy('patient:patient_list'))

patient/templates/patient/index.html
<div class="container">
	<table class="table table-striped">
		<thead>
		<tr align="middle">
			<td><B>Appointment ID</B></td>
			<td><B>Patient Name</B></td>
			<td><B>Doctor Name</B></td>
			<td><B>Appointment_Date</B></td>
			<td><B>Created_Date ID</B></td>
			<td><B>Updated_Date ID</B></td>
		</tr>
		</thead>
	</table>
</div>

patient/templates/patient/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>{% block title %}{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6.js/bootstrap.min.js"></script>
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">PVTS</a>&nbsp
        </div>
        {% if user.is_authenticated %}
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'view_profile' %}">Profile</a></li>&nbsp
            <li><a class="navbar-brand" href="{% url 'doctor:doctor_list' %}">Doctor</a><li>&nbsp
            <li><a class="navbar-brand" href="{% url 'appointment:appointment_list' %}">Appointment</a><li>&nbsp
            <li><a class="navbar-brand" href="{% url 'examination:examination_list' %}">Examination</a><li>&nbsp
            <li><a class="navbar-brand" href="{% url 'diagnosis:diagnosis_list' %}">Diagnosis</a><li>&nbsp
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/account/logout/">Logout</a></li>&nbsp
          </ul>
        </div><!--/.nav-collapse -->
        {% else %}
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/account/login/">Login</a></li>
            <li><a href="/account/register">Register</a></li>
          </ul>
        {% endif %}
      </div>
    </nav>
    <div style="padding-top:100px">
    </div>
	{% block content %}
	{% endblock %}

	<hr/>
</body>
</html>

patient/templates/patient/patient_confirm_delete.html
{% extends "patient/layout.html" %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<form action="" method="post">
                {% csrf_token %}
                <div class="alert alert-danger">
                Are you really sure to delete it?
                </div>
                <table>
                    {{ form.as_table }}
                </table>
                <input type="submit" value="Delete" class="btn btn-primary"/>
                <a href="{% url "patient:patient_list" %}" class="btn btn-primary">Back to the List</a>
            </form>
		</div>
	</div>
</div>

{% endblock %}

patient/templates/patient/patient_detail.html
{% extends "patient/layout.html" %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>Patient ID : {{ patient.patient_id}}</h1>
        <div class="form-group">
            <label for="">First Name</label>
            <input type="text" name="fname" value="{{ patient.fname }}" class="form-control" id="fname" placeholder="">
        </div>
        <div class="form-group">
            <label for="">Middle Name</label>
            <input type="text" name="Mname" value="{{ patient.mname }}" class="form-control" id="Mname" placeholder="">
        </div>
        <div class="form-group">
            <label for="">Last Name</label>
            <input type="text" name="lname" value="{{ patient.lname }}" class="form-control" id="lname" placeholder="">
        </div>
        <div class="form-group">
            <label for="">Date of Birth</label>
            <input type="text" name="mname" value="{{ patient.dob }}" class="form-control" id="dob" placeholder="">
        </div>
        <div class="form-group">
            <label for="">Sex</label>
            <input type="text" name="mname" value="{{ patient.sex }}" class="form-control" id="sex" placeholder="">
        </div>
        <div class="form-group">
            <label for="">Address 1</label>
            <input type="text" name="mname" value="{{ patient.addr1 }}" class="form-control" id="addr1" placeholder="">
        </div>
        <div class="form-group">
            <label for="">Address 2</label>
            <input type="text" name="mname" value="{{ patient.addr2 }}" class="form-control" id="addr2" placeholder="">
        </div>
        <div class="form-group">
            <label for="">Address 3</label>
            <input type="text" name="mname" value="{{ patient.addr3 }}" class="form-control" id="addr3" placeholder="">
        </div>
        <div class="form-group">
            <label for="">City</label>
            <input type="text" name="city" value="{{ patient.city }}" class="form-control" id="city" placeholder="">
        </div>
        <div class="form-group">
            <label for="">State</label>
            <input type="text" name="state" value="{{ patient.state }}" class="form-control" id="state" placeholder="">
        </div>
        <div class="form-group">
            <label for="">Country</label>
            <input type="text" name="country" value="{{ patient.country }}" class="form-control" id="country" placeholder="">
        </div>
        <div class="form-group">
            <label for="">Telephone Number</label>
            <input type="text" name="phone1" value="{{ patient.phone1 }}" class="form-control" id="phone1" placeholder="">
        </div>
        <div class="form-group">
            <label for="">Phone2</label>
            <input type="text" name="phone2" value="{{ patient.phone2 }}" class="form-control" id="phone2" placeholder="">
        </div>
        <div class="form-group">
            <label for="">Phone3</label>
            <input type="text" name="phone3" value="{{ patient.phone3 }}" class="form-control" id="phone3" placeholder="">
        </div>
          <hr/>
          <a href="{% url "patient:patient_list" %}" class="btn btn-primary">List</a>
          <a href="{% url "patient:patient_edit" patient.pk patient.pk %}" class="btn btn-primary">Edit</a>
          <a href="{% url "patient:patient_delete" patient.pk patient.pk %}" class="btn btn-primary">Delete</a>
    </div>
  </div>
</div>
{% endblock %}

patient/templates/patient/patient_form.html
{% extends "patient/layout.html" %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<form action="" method="post">
	        {% csrf_token %}
	            <table>
		        {{ form.as_table }}
	            </table>
            <input type="submit" />
            </form>
		</div>
	</div>
</div>

{% endblock %}

patient/templates/patient/patient_list.html
{% extends "patient/layout.html" %}

{% block head %}
<title>Patient</title>
{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-sm-12">
        <h1>Patient</h1>
			<table class="table table-striped table-bordered">
				<a href="{% url "patient:patient_new" %}" class="btn btn-primary">Add Patient</a>
			</table>
			<table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Patient Number</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Date of Birth</th>
                    </tr>
                </thead>
                <tbody>
			    {% for patient in patient_list %}
                    <tr>
                        <td width="130" align="center"><a href="{% url "patient:patient_detail" patient.pk %}">{{ patient.pk}}</a></td>
                        <td>{{ patient.fname}}</td>
                        <td>{{ patient.lname}}</td>
                        <td>{{ patient.dob}}</td>
                    </tr>
			    {% endfor %}
                </tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}